version: '3.8'

services:
  runners:
    privileged: true
    restart: always
    build: .
    env_file:
      - .env
    volumes:
      - ${GITLAB_RUNNER_CONFIG_DIR}:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock # for Docker in Docker containers
    
    ports:
      - ${RUNNERS_SERVICE_PORT}:8093

